version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=busappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=321Kacper
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: web:busapp-docker
    container_name: bus-container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

